### ISSUE TITLE
Different sub sub menu item colour

### ISSUE THREAD

**Issue by thpweb1** [CrocoBlock/suggestions#3410]
In JetMenu, when a menu is created with a sub menu and one of the items on the sub menu has it's own sub menu, when you go to one of the sub sub menu pages, all the sub sub menu items are displaying as active. Only the page that the sub sub menu item relates to, should be active.

![croco sub menu issue](https://user-images.githubusercontent.com/67333429/120359285-6a409b00-c2ff-11eb-801e-1c4c791876c4.jpg)

**Comment by rtpHarry** [comment]
I'm noticing this as well and it seems to be that it is missing a `>` in the styles.

I have recorded a quick video showing the situation:

https://soapbox.wistia.com/videos/QnPSA2GAxM

Here is the modified css snippet

<img width="487" alt="image" src="https://github.com/Crocoblock/suggestions/assets/1038062/60bea130-5e98-4651-8ae9-45bb97df193c">

Unfortunately I cannot do that to the actual site so I'll have to write custom css to style this while its broken.

I've settled on this:

```css
selector .jet-menu li.jet-sub-menu-item.jet-current-menu-item.jet-menu-item-has-children > .sub-level-link,
selector .jet-menu li.jet-sub-menu-item.jet-current_page_item > .sub-level-link{
    color: var(--e-global-color-d03a1e8 );
    background-color: var(--e-global-color-d5426f0 );
}
```

However, this is just for my specific scenario, where the client has put some wordpress-nested-pages out of the hierarchy with the menu structure.

For normal readers with correctly structure menu's, this will probably do whats needed:

First - go in and reset the color and background colour to default on the sub menu active item so its not set.

Then use some code like this in the custom css section:

```css
selector .jet-menu li.jet-sub-menu-item.jet-current-menu-item > .sub-level-link{
    color: var(--e-global-color-d03a1e8 );
    background-color: var(--e-global-color-d5426f0 );
}
```
