### ISSUE TITLE
Horizontal Scrolling and Center Mode in Jet Smart Filters

### ISSUE THREAD

**Issue by GOHA81177** [CrocoBlock/suggestions#4142]
Please add several filter display functions to Jet Smart Filters
Namely Horizontal Scrolling and Center Mode
For a more correct display of content.

Thank you very much!
![Скрол](https://user-images.githubusercontent.com/47380983/136786134-3cb897c0-5e6b-4fe1-8eb0-77c7f73ea124.png)

**Comment by saqi-sn** [comment]
@media only screen and (max-width: 600px) {
.jet-radio-list{
overflow-x: scroll;
overflow-y: hidden;
}
.jet-radio-list-wrapper fieldset {
    margin: 0;
    border: 0;
    padding-bottom: 20px!important;
    display: flex;
    flex-direction: row;
    width: max-content;
    justify-content: flex-start;
    align-items: center;
}
.jet-radio-list .jet-radio-list__item{
    width: max-content;
}}



you can use this CSS here

**Comment by saqi-sn** [comment]
```css
@media only screen and (max-width: 600px) {
.jet-radio-list{
overflow-x: scroll;
overflow-y: hidden;
}
.jet-radio-list-wrapper fieldset {
    margin: 0;
    border: 0;
    padding-bottom: 20px!important;
    display: flex;
    flex-direction: row;
    width: max-content;
    justify-content: flex-start;
    align-items: center;
}
.jet-radio-list .jet-radio-list__item{
    width: max-content;
}}
``` 

you can use this CSS here
