### ISSUE TITLE
JetElements: add missing size units to Inline SVG widget

### ISSUE THREAD

**Issue by stijnvanouplines** [CrocoBlock/suggestions#7936]
To my surprise, the Inline SVG widget in JetElements only allows pixel values for the gap between items. I went ahead and added support for additional values in the [code](https://gist.github.com/stijnvanouplines/0ff1e4eb1a646b0e5efbc2024fba862d). It would be great if you could consider merging these changes into core.

**Comment by stijnvanouplines** [comment]
I also noticed a small gap underneath the SVG caused by the line-height set on the body. The following custom CSS resolves the issue. Perhaps it could be added to the core as well?

```css
selector .elementor-jet-inline-svg {
    font-size: 0;
    line-height: 1;
}
```
