### ISSUE TITLE
JetFormBuilder - Add Option to Hide Form Labels

### ISSUE THREAD

**Issue by RicoGL** [CrocoBlock/suggestions#8154]
**Before adding a new feature request, please, make sure you’ve checked:**

- ✅ The feature is not currently in the JetFormBuilder backlog or listed in the changelog.
- ✅ This specific functionality is not yet available in the current version of JetFormBuilder.

**Please, describe the feature request, making it clear to understand.**

Feature Name: Add an option to visually hide form labels (but keep them accessible to screen readers)

Product: JetFormBuilder

**Description:**
I would like to request a new feature for JetFormBuilder that allows users to hide form labels from the visual UI while still keeping them accessible to screen readers. This is especially important for improving the visual design of forms while maintaining accessibility compliance (e.g., WCAG 2.1).

Currently, hiding labels requires manual CSS overrides, which may not be intuitive for all users and introduces risk of accessibility issues if not done correctly. Adding a built-in toggle option per field or global (e.g., “Hide label visually (accessible to screen readers)”) would provide a much-needed balance between design flexibility and accessibility best practices.

**Add an example of where this feature is already implemented.**

Many form plugins such as like Elementor Pro include this exact feature, labeled “Hide Label”. However, they ensure the label is still included in the DOM for screen readers via accessibility-focused CSS classes (e.g., .sr-only).

Proposed CSS to be included or recommended in documentation:

```css
.visually-hidden {
  position: absolute !important;
  width: 1px !important;
  height: 1px !important;
  padding: 0 !important;
  margin: -1px !important;
  overflow: hidden !important;
  clip: rect(0, 0, 0, 0) !important;
  white-space: nowrap !important;
  border: 0 !important;
}
```

Developers could use this class on the label element when the “Hide visually” toggle is enabled. Alternatively, JetFormBuilder could automatically apply this styling when the option is selected in the form builder interface.

**Use Case / Justification:**
This feature is particularly helpful for designers or site owners who use placeholder text instead of visible labels but still want to comply with accessibility standards. The goal is to streamline the development of accessible forms without requiring advanced CSS knowledge or risking non-compliance.

**Conclusion:**
Adding a built-in option to visually hide labels but keep them accessible will improve accessibility, design flexibility, and user-friendliness of JetFormBuilder.

Thank you for considering this request.
